version: '3'


services:
  orders-db:
    container_name: orders_database
    image: postgres:16.2
    # esto hace que cada que se abra el docker se levante esta img
    restart: always
    volumes:
      #  ./postgres: esto es que lo voy a guardar en la raíz del proyecto en una carpeta postgres, /var/lib/postgresql/data esta info sale de la img del contenedor
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=orders_user
      - POSTGRES_PASSWORD=orders_password
      - POSTGRES_DB=orders_db